steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud', 'run', 'deploy', 'backend',
        '--image=gcr.io/$PROJECT_ID/backend',
        '--platform=managed',
        '--region=asia-southeast2',
        '--allow-unauthenticated'
      ]

images:
  - gcr.io/$PROJECT_ID/backend
